### ISSUE TITLE
No such module 'AppKit' in 2.0.0

### ISSUE THREAD

**Issue by phin** [hodinkee/iris#16]
After updating to the lastest release on master, our app doesn't compile, bevause of the import AppKit and NSColor extensions in NSColor.swift.

It used to work fine in 1.2.0 and the Swift3 branch, our project uses 3.0.0

Thanks!

**Comment by calebd** [comment]
How are you including Iris in your project?

**Comment by calebd** [comment]
Looks like CocoaPods. Podspec will be correct in the 2.0.0 release. Good catch!
